# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/0b6bf05d-c836-4c2c-b937-2dabb2a30530";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f770aee4-e041-4300-8c07-cedc2baa51b2".device = "/dev/disk/by-uuid/f770aee4-e041-4300-8c07-cedc2baa51b2";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/BA48-8DD1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  #  swapDevices =
  #   [ { device = "/dev/disk/by-uuid/93414de3-5904-4d40-9244-add04b242d20"; }
  #  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;


  # Enable OpenGL hardware
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = ["nvidia"];

  # Enable NVIDIA proprietary driver
  hardware.nvidia = {
    # Enable proprietary driver modules
    open = false;
    # Enable kernel modesetting
    modesetting.enable = true;
    nvidiaSettings = true;
  };

  # ... other configuration options


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;
  services.fwupd.enable = true;
}
